# this file contains the config specific to running in "production" at github
title: "Akka"

markdown: kramdown

# The base URL should only be set if the site is deployed at a subpath
# See http://ben.balter.com/jekyll-style-guide/config/#baseurl.
# For devel baseurl: "" is used by passing --baseurl "" to jekyll
baseurl: ""

gems:
- jekyll-redirect-from

sass:
  sass_dir: resources/stylesheets
  style: compressed

exclude:
- README
- vendor

# format for blog permalinks (no .html at the end)
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

defaults:
-
  scope:
    path: "" # all files
  values:
    # note that changing this requires a jekyll restart to be picked up if serving locally
    # versions.json will be updated as long as the changes here are patch versions, for minor and major it needs to
    # be updated manually
    current_akka_version: 2.5.7
    current_akka_http_version: 10.0.11
    previous_akka_version: 2.4.20
    current_java_scala_version: 2.12 # used for deps for Java
